name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install --no-interaction

    - name: Lint with flake8
      run: |
        poetry run flake8 apiki/ --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 apiki/ --count --max-complexity=10 --max-line-length=79 --statistics

    - name: Check formatting with black
      run: |
        poetry run black apiki/ --check --diff

    - name: Sort imports with isort
      run: |
        poetry run isort apiki/ --check --diff

    - name: Type check with mypy
      run: |
        poetry run mypy apiki/

    - name: Test with pytest
      run: |
        poetry run pytest --cov=apiki/ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
